language: csharp
solution: ./src/Panda.DevUtil.sln
script:
  - xbuild /p:Configuration=Release ./src/Panda.DevUtil.sln
  - mono ./src/packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./src/Panda.DevUtil.Test/bin/Release/Panda.DevUtil.Test.dll
services:
  - redis-server
